# Generated by Django 5.2.16 on 2026-07-28 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(db_column='itemName', max_length=100)),
                ('tag', models.CharField(blank=True, db_column='tag', max_length=200, null=True)),
            ],
            options={
                'db_table': 'tbItem',
            },
        ),
        migrations.CreateModel(
            name='LearningPlanList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learningPlanName', models.CharField(db_column='learningPlanName', max_length=100)),
                ('tag', models.CharField(blank=True, db_column='tag', max_length=200, null=True)),
            ],
            options={
                'db_table': 'tbLearningPlanList',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(db_column='subjectName', max_length=50)),
                ('tag', models.CharField(blank=True, db_column='tag', max_length=200, null=True)),
            ],
            options={
                'db_table': 'tbSubject',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(db_column='userName', max_length=80, unique=True)),
                ('userPW', models.CharField(db_column='userPW', max_length=120)),
                ('userEmail', models.CharField(db_column='userEmail', max_length=120, unique=True)),
            ],
            options={
                'db_table': 'tbUser',
            },
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.IntegerField(db_column='begin')),
                ('end', models.IntegerField(db_column='end')),
                ('tag', models.CharField(blank=True, db_column='tag', max_length=200, null=True)),
                ('item', models.ForeignKey(db_column='itemId', on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='planner.item')),
            ],
            options={
                'db_table': 'tbScope',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='subject',
            field=models.ForeignKey(db_column='subId', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planner.subject'),
        ),
        migrations.CreateModel(
            name='TimeTableList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeTableName', models.CharField(db_column='timeTableName', max_length=100)),
                ('tag', models.CharField(blank=True, db_column='tag', max_length=200, null=True)),
                ('learning_plan', models.ForeignKey(db_column='learningPlanListID', on_delete=django.db.models.deletion.CASCADE, related_name='time_tables', to='planner.learningplanlist')),
            ],
            options={
                'db_table': 'tbTimeTableList',
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(db_column='day')),
                ('sTime', models.IntegerField(db_column='sTime')),
                ('eTime', models.IntegerField(db_column='eTime')),
                ('tag', models.CharField(blank=True, db_column='tag', max_length=200, null=True)),
                ('item', models.ForeignKey(db_column='itemId', on_delete=django.db.models.deletion.CASCADE, related_name='time_tables', to='planner.item')),
                ('time_table_list', models.ForeignKey(db_column='timeTableListId', on_delete=django.db.models.deletion.CASCADE, related_name='time_tables', to='planner.timetablelist')),
            ],
            options={
                'db_table': 'tbTimeTable',
            },
        ),
        migrations.AddField(
            model_name='learningplanlist',
            name='user',
            field=models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, related_name='learning_plans', to='planner.user'),
        ),
    ]
