# Generated by Django 5.2.16 on 2026-07-28 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_subject_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablelist',
            name='user',
            field=models.ForeignKey(blank=True, db_column='userID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_table_lists', to='planner.user'),
        ),
        migrations.AlterField(
            model_name='timetablelist',
            name='learning_plan',
            field=models.ForeignKey(blank=True, db_column='learningPlanListID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_tables', to='planner.learningplanlist'),
        ),
    ]
